default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: sample_app_development
  username: rails_dev
  password: $rails!dev
test:
  <<: *default
  database: sample_app_test
  username: rails_dev
  password: $rails!dev
production:
  <<: *default
  database: sample_app_production
  username: sample_app
  password: <%= ENV['SAMPLE_APP_DATABASE_PASSWORD'] %>
